#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="docker/development/compose.yaml"
SERVICE_NAME="app"

function show_help() {
  echo
  echo "Usage:"
  echo "  $0 start              Start the development server"
  echo "  $0 stop               Stop the development server"
  echo "  $0 enter              Enter the container shell"
	echo "  $0 logs	              Show service logs"
  echo "  $0 ps                 List running services"
  echo "  $0 docker <command>   Run command inside the container"
  echo "  $0 <compose args>     Pass any other argument to docker compose"
  echo
  exit 0
}

if [[ $# -eq 0 ]]; then
  show_help
fi

case "$1" in
  help|-h|--help)
    show_help
    ;;
  start)
    docker compose -f "$COMPOSE_FILE" up -d --build
    docker compose -f "$COMPOSE_FILE" exec "$SERVICE_NAME" sh
    ;;
  stop)
    docker compose -f "$COMPOSE_FILE" down
    ;;
  enter)
    docker compose -f "$COMPOSE_FILE" exec "$SERVICE_NAME" sh
    ;;
	logs)
		docker compose -f "$COMPOSE_FILE" logs "$SERVICE_NAME" -f
		;;
  ps)
    docker compose -f "$COMPOSE_FILE" ps
    ;;
  docker)
    shift
    docker compose -f "$COMPOSE_FILE" run --rm "$SERVICE_NAME" "$@"
    ;;
  *)
    docker compose -f "$COMPOSE_FILE" "$@"
    ;;
esac
